using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Principal;
using System.ServiceModel;
using System.Text;
using System.Threading;
using System.Threading.Tasks;

namespace SyslogClient
{
    class Program
    {
        static void Main(string[] args)
        {
            NetTcpBinding binding = new NetTcpBinding();

            EndpointAddress address = new EndpointAddress(new Uri("net.tcp://localhost:2110/IWCFContract"));
            string eventData = "-1";
            int e = -1;
            using (WCFClient proxy = new WCFClient(binding, address))
            {
                while (true)
                {

                    while(Int32.Parse(eventData) < 1 || Int32.Parse(eventData) > 5)
                    {
                        Console.WriteLine("Make new event: ");
                        Console.WriteLine("1. User level messages");
                        Console.WriteLine("2. Security/Authorization messages");
                        Console.WriteLine("3. Messages generated by syslog");
                        Console.WriteLine("4. Log audit");
                        Console.WriteLine("5. Log alert");

                        eventData = Console.ReadLine();
                    }

                    
                    Console.WriteLine("Enter message: ");
                    string messText = Console.ReadLine();               

                    proxy.SendMessage(eventData + messText);
                    eventData = "-1";
                }
            }

        }
    }
}
